
Vagrant.configure("2") do |config|

      config.vm.define "haproxy01" do |haproxy01|
       haproxy01.vm.box = "percyperezd/oraclelinux6"
       haproxy01.vm.hostname = "haproxy01"
       haproxy01.vm.network "private_network", ip: "192.168.56.21"
       haproxy01.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.cpus = "2"
          vb.linked_clone = true
          vb.name = "haproxy01"
        end
      end

      config.vm.provision "ansible" do |ansible|
       ansible.playbook = "../../../ansible/ansible_deploy_vagrant/create-user-vagrant.yml"
       ansible.host_vars = {
         "haproxy01" => {"ansible_python_interpreter" => "/usr/bin/python2.7", "remove_ip" => "192.168.56.21", "install_pkg" => "false"},
       }
    end
end
