Vagrant.configure("2") do |config|
   config.vm.define "web" do |web|
      web.vm.box = "generic/debian11"
      web.vm.hostname = "lnxdebian11"
      web.vm.network "private_network", ip: "192.168.56.24"
      web.vm.provider "virtualbox" do |vb|
          vb.memory = "512"
          vb.cpus = "1"
          vb.linked_clone = true
          vb.name = "lnxdebian11"
      end
   end
 config.vm.provision "ansible" do |ansible|
  ansible.playbook = "../../../ansible/ansible_deploy_vagrant/create-user-vagrant.yml"
#  ansible.verbose = "vvv"
  ansible.host_vars = {
    "web" => {"remove_ip"=>"192.168.56.24",
              "install_pkg"=>"true" 
              }
  }
 end
end
