Vagrant.configure("2") do |config|
   config.vm.define "ubnt" do |ubnt|
      ubnt.vm.synced_folder '.', '/vagrant', disabled: true
      ubnt.vm.box = "ubuntu/lunar64"
      ubnt.vm.hostname = "lnxubuntu2304"
      ubnt.vm.network "private_network", ip: "192.168.56.29"
      ubnt.vm.provider "virtualbox" do |vb|
          vb.memory = "512"
          vb.cpus = "1"
          vb.linked_clone = true
          vb.name = "lnxubuntu2304"
      end
   end
 config.vm.provision "ansible" do |ansible|
    ansible.playbook = "/home/eflores/git.personal/ansible_for_unix/ansible_deploy_vagrant/create-user-vagrant.yml"
  ansible.host_vars = {
    "ubnt" => {"remove_ip"=>"192.168.56.29",
              "install_pkg"=>"true"
              }
  }
    ansible.vault_password_file = "/etc/vault.txt"
 end
end
