Vagrant.configure("2") do |config|
   config.vm.define "web" do |web|
      web.vm.box = "jonatasbaldin/solaris11"
      web.vm.hostname = "solaris"
      web.vm.network "private_network", ip: "192.168.56.12"
      web.vm.provider "virtualbox" do |vb|
          vb.memory = "512"
          vb.cpus = "1"
          vb.linked_clone = true
          vb.name = "solaris"
      end
   end
 config.vm.provision "ansible" do |ansible|
  ansible.playbook = "../../../ansible/ansible_deploy_vagrant/create-user-vagrant.yml"
  ansible.host_vars = {
    "web" => {"remove_ip"=>"192.168.56.12",
              "install_pkg"=>"true"
              }
  }
 end
end
